# Generated by Django 3.2 on 2021-04-23 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('brgy', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('houseno', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('birth', models.DateField()),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccine')),
            ],
        ),
    ]
